version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
